import { StyleSheet } from 'react-native';
import { Colors } from '../../../utils/Colors';
import {
  normalizeFont,
  normalizeHeight,
  normalizeWidth,
  pixelSizeX,
  pixelSizeY,
} from '../../../utils/index';
import { Typography } from '../../../utils/typography';

export const useStyles = () => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.background,
      marginTop: pixelSizeY(14),
    },
    content: {
      flex: 1,
      paddingHorizontal: pixelSizeX(16),
    },
    topSpacer: {
      height: normalizeHeight(10),
    },
    logoContainer: {
      alignItems: 'center',
      marginBottom: pixelSizeY(20),
    },
    logoIcon: {
      width: normalizeWidth(64),
      height: normalizeHeight(64),
      backgroundColor: Colors.primary,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: pixelSizeY(8),
    },
    logoEmoji: {
      fontSize: normalizeFont(32),
    },
    logoText: {
      fontSize: normalizeFont(16),
      fontWeight: '600' as const,
      color: '#5719e5',
    },
    header: {
      alignItems: 'center',
      marginBottom: pixelSizeY(20),
    },
    title: {
      fontSize: normalizeFont(24),
      fontFamily: Typography.fontfamily.jakarta.jakartaBold,
      color: Colors.black,
      textAlign: 'center',
      marginBottom: pixelSizeY(12),
      lineHeight: normalizeFont(30),
    },
    subtitle: {
      fontSize: normalizeFont(16),
      fontFamily: Typography.fontfamily.jakarta.jakartaRegular,
      color: Colors.black,
      textAlign: 'center',
      lineHeight: normalizeFont(24),
      paddingHorizontal: pixelSizeY(8),
    },
    codeContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: pixelSizeX(16),
      marginBottom: pixelSizeY(20),
    },
    codeInput: {
      width: normalizeWidth(48),
      height: normalizeHeight(56),
      backgroundColor: '#fafafa',
      borderColor: '#d9d4e3',
      borderWidth: 1,
      borderRadius: 12,
      fontSize: normalizeFont(18),
      fontWeight: 'bold' as const,
      color: '#120f17',
      textAlign: 'center',
    },
    codeInputFilled: {
      backgroundColor: '#ffffff',
      borderColor: '#5719e5',
      borderWidth: 2,
    },
    verifyButton: {
      height: normalizeHeight(48),
      backgroundColor: Colors.primary,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: pixelSizeY(24),
      marginTop: pixelSizeY(24),
    },
    verifyButtonDisabled: {
      backgroundColor: Colors.border,
    },
    verifyButtonText: {
      fontSize: normalizeFont(16),
      fontFamily: Typography.fontfamily.jakarta.jakartaSemibold,
      color: Colors.white,
    },
    timerContainer: {
      alignItems: 'center',
      marginTop: pixelSizeY(14),
      marginBottom: pixelSizeY(8),
    },
    timerBox: {
      width: normalizeWidth(65),
      height: normalizeHeight(65),
      backgroundColor: Colors.secondaryGrey,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: pixelSizeY(12),
    },
    timerText: {
      fontSize: normalizeFont(18),
      color: Colors.black,
      fontFamily: Typography.fontfamily.jakarta.jakartaBold,
    },
    secondsText: {
      fontSize: normalizeFont(14),
      color: Colors.black,
      fontFamily: Typography.fontfamily.jakarta.jakartaRegular,
      textAlign: 'center',
    },
    resendContainer: {
      alignItems: 'center',
      paddingVertical: pixelSizeY(18),
    },
    resendContainerVerificationPassword: {
      alignItems: 'center',
      paddingBottom: pixelSizeY(18),
    },
    resendText: {
      fontSize: normalizeFont(14),
      color: Colors.grey,
      textAlign: 'center',
      lineHeight: normalizeFont(21),
      fontFamily: Typography.fontfamily.jakarta.jakartaRegular,
    },
    resendTextDisabled: {
      color: Colors.border,
    },
    passwordSection: {
      marginTop: pixelSizeY(16),
    },
    passwordSectionTitle: {
      fontSize: normalizeFont(16),
      fontFamily: Typography.fontfamily.jakarta.jakartaBold,
      color: Colors.black,
      textAlign: 'center',
      marginBottom: pixelSizeY(20),
      lineHeight: normalizeFont(24),
    },
    inputContainer: {
      flexDirection: 'row',
      marginBottom: pixelSizeY(8),
      alignItems: 'center',
    },
    inputWrapper: {
      flex: 1,
      backgroundColor: Colors.background,
      borderColor: Colors.border,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: pixelSizeX(16),
      paddingVertical: pixelSizeY(16),
      borderTopRightRadius: 0,
      borderBottomRightRadius: 0,
      borderRightWidth: 0,
    },
    passwordContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: pixelSizeY(10),
      backgroundColor: Colors.background,
      borderRadius: pixelSizeX(12),
    },
    passwordInput: {
      flex: 1,
      height: normalizeHeight(64),
      borderWidth: 1,
      borderTopLeftRadius: pixelSizeX(12),
      borderBottomLeftRadius: pixelSizeX(12),
      borderRightWidth: 0,
      paddingHorizontal: pixelSizeX(16),
      fontSize: normalizeFont(16),
      color: Colors.black,
      backgroundColor: Colors.background,
      borderColor: Colors.inputBorder,
      fontFamily: Typography.fontfamily.jakarta.jakartaRegular,
    },
    eyeButton: {
      height: normalizeHeight(64),
      width: normalizeWidth(56),
      backgroundColor: Colors.background,
      borderColor: Colors.inputBorder,
      borderWidth: 1,
      borderTopRightRadius: 12,
      borderBottomRightRadius: 12,
      borderLeftWidth: 0,
      alignItems: 'center',
      justifyContent: 'center',
    },
    eyeIcon: {
      fontSize: normalizeFont(16),
    },
    savePasswordButton: {
      height: normalizeHeight(48),
      backgroundColor: Colors.primary,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: pixelSizeY(24),
      marginTop: pixelSizeY(16),
    },
    savePasswordButtonDisabled: {
      backgroundColor: Colors.grey,
    },
    savePasswordButtonText: {
      fontSize: normalizeFont(16),
      fontFamily: Typography.fontfamily.jakarta.jakartaBold,
      color: Colors.white,
    },
    error: {
      fontSize: normalizeFont(13),
      fontFamily: Typography.fontfamily.jakarta.jakartaRegular,
      color: Colors.error,
      marginBottom: pixelSizeY(8),
    },
    cell: {
      borderColor: `${Colors.inputBorder}`,
      borderRadius: pixelSizeY(10),
      borderWidth: 1,
      color: Colors.black,
      fontSize: normalizeFont(24),
      fontFamily: Typography.fontfamily.jakarta.jakartaRegular,
      height: normalizeHeight(52),
      lineHeight: pixelSizeY(42),
      margin: 0,
      padding: 0,
      paddingTop: pixelSizeY(4),
      textAlign: 'center',
      width: normalizeWidth(50),
    },
    codeFieldRoot: {},
    otpContainer: {
      paddingVertical: pixelSizeY(6),
    },
  });
};
